/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BankAccount
 */
export interface BankAccount {
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof BankAccount
     */
    id: number;
    /**
     * Name of the Bank Account
     * @type {string}
     * @memberof BankAccount
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    institutionId: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    institutionName: string | null;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    kind?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BankAccount
     */
    archived: boolean;
    /**
     * 
     * @type {Date}
     * @memberof BankAccount
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BankAccount
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof BankAccount
     */
    _default: boolean;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    type?: BankAccountTypeEnum | null;
}

/**
* @export
* @enum {string}
*/
export enum BankAccountTypeEnum {
    Checking = 'checking',
    Savings = 'savings',
    Other = 'other'
}


/**
 * Check if a given object implements the BankAccount interface.
 */
export function instanceOfBankAccount(value: object): value is BankAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('institutionId' in value) || value['institutionId'] === undefined) return false;
    if (!('institutionName' in value) || value['institutionName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('_default' in value) || value['_default'] === undefined) return false;
    return true;
}

export function BankAccountFromJSON(json: any): BankAccount {
    return BankAccountFromJSONTyped(json, false);
}

export function BankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'institutionId': json['institution_id'],
        'institutionName': json['institution_name'],
        'description': json['description'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'archived': json['archived'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        '_default': json['default'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function BankAccountToJSON(json: any): BankAccount {
    return BankAccountToJSONTyped(json, false);
}

export function BankAccountToJSONTyped(value?: BankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'institution_id': value['institutionId'],
        'institution_name': value['institutionName'],
        'description': value['description'],
        'kind': value['kind'],
        'archived': value['archived'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'default': value['_default'],
        'type': value['type'],
    };
}

