/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating or updating a bank account
 * @export
 * @interface BankAccountInput
 */
export interface BankAccountInput {
    /**
     * Name of the Bank Account
     * @type {string}
     * @memberof BankAccountInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountInput
     */
    institutionId?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccountInput
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BankAccountInput
     */
    archived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BankAccountInput
     */
    _default?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BankAccountInput
     */
    type?: BankAccountInputTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum BankAccountInputTypeEnum {
    Checking = 'checking',
    Savings = 'savings',
    Other = 'other'
}


/**
 * Check if a given object implements the BankAccountInput interface.
 */
export function instanceOfBankAccountInput(value: object): value is BankAccountInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function BankAccountInputFromJSON(json: any): BankAccountInput {
    return BankAccountInputFromJSONTyped(json, false);
}

export function BankAccountInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccountInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'institutionId': json['institution_id'] == null ? undefined : json['institution_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        '_default': json['default'] == null ? undefined : json['default'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function BankAccountInputToJSON(json: any): BankAccountInput {
    return BankAccountInputToJSONTyped(json, false);
}

export function BankAccountInputToJSONTyped(value?: BankAccountInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'institution_id': value['institutionId'],
        'description': value['description'],
        'archived': value['archived'],
        'default': value['_default'],
        'type': value['type'],
    };
}

