/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Budget
 */
export interface Budget {
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    amountInCents?: number;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    categoryId?: number;
    /**
     * 
     * @type {Date}
     * @memberof Budget
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    activityType?: number;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof Budget
     */
    predictedTotal?: number;
    /**
     * 
     * @type {string}
     * @memberof Budget
     */
    percentage?: string;
}

/**
 * Check if a given object implements the Budget interface.
 */
export function instanceOfBudget(value: object): value is Budget {
    return true;
}

export function BudgetFromJSON(json: any): Budget {
    return BudgetFromJSONTyped(json, false);
}

export function BudgetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Budget {
    if (json == null) {
        return json;
    }
    return {
        
        'amountInCents': json['amount_in_cents'] == null ? undefined : json['amount_in_cents'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'activityType': json['activity_type'] == null ? undefined : json['activity_type'],
        'total': json['total'] == null ? undefined : json['total'],
        'predictedTotal': json['predicted_total'] == null ? undefined : json['predicted_total'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
    };
}

export function BudgetToJSON(json: any): Budget {
    return BudgetToJSONTyped(json, false);
}

export function BudgetToJSONTyped(value?: Budget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_in_cents': value['amountInCents'],
        'category_id': value['categoryId'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'activity_type': value['activityType'],
        'total': value['total'],
        'predicted_total': value['predictedTotal'],
        'percentage': value['percentage'],
    };
}

