/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating or updating a category
 * @export
 * @interface CategoryInput
 */
export interface CategoryInput {
    /**
     * 
     * @type {string}
     * @memberof CategoryInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryInput
     */
    color: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryInput
     */
    parentId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CategoryInput
     */
    groupId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryInput
     */
    fixed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CategoryInput
     */
    essential?: boolean;
}

/**
 * Check if a given object implements the CategoryInput interface.
 */
export function instanceOfCategoryInput(value: object): value is CategoryInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    return true;
}

export function CategoryInputFromJSON(json: any): CategoryInput {
    return CategoryInputFromJSONTyped(json, false);
}

export function CategoryInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'color': json['color'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
        'fixed': json['fixed'] == null ? undefined : json['fixed'],
        'essential': json['essential'] == null ? undefined : json['essential'],
    };
}

export function CategoryInputToJSON(json: any): CategoryInput {
    return CategoryInputToJSONTyped(json, false);
}

export function CategoryInputToJSONTyped(value?: CategoryInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'color': value['color'],
        'parent_id': value['parentId'],
        'group_id': value['groupId'],
        'fixed': value['fixed'],
        'essential': value['essential'],
    };
}

