/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    color: string;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    parentId: number | null;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    groupId: string;
    /**
     * 
     * @type {boolean}
     * @memberof Category
     */
    fixed: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Category
     */
    essential: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Category
     */
    _default: boolean;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    kind: CategoryKindEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Category
     */
    archived: boolean;
}

/**
* @export
* @enum {string}
*/
export enum CategoryKindEnum {
    Expenses = 'expenses',
    Earnings = 'earnings',
    None = 'none'
}


/**
 * Check if a given object implements the Category interface.
 */
export function instanceOfCategory(value: object): value is Category {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('groupId' in value) || value['groupId'] === undefined) return false;
    if (!('fixed' in value) || value['fixed'] === undefined) return false;
    if (!('essential' in value) || value['essential'] === undefined) return false;
    if (!('_default' in value) || value['_default'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('archived' in value) || value['archived'] === undefined) return false;
    return true;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'color': json['color'],
        'parentId': json['parent_id'],
        'groupId': json['group_id'],
        'fixed': json['fixed'],
        'essential': json['essential'],
        '_default': json['default'],
        'uuid': json['uuid'],
        'kind': json['kind'],
        'archived': json['archived'],
    };
}

export function CategoryToJSON(json: any): Category {
    return CategoryToJSONTyped(json, false);
}

export function CategoryToJSONTyped(value?: Category | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'color': value['color'],
        'parent_id': value['parentId'],
        'group_id': value['groupId'],
        'fixed': value['fixed'],
        'essential': value['essential'],
        'default': value['_default'],
        'uuid': value['uuid'],
        'kind': value['kind'],
        'archived': value['archived'],
    };
}

