/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InstallmentTransaction } from './InstallmentTransaction';
import {
    instanceOfInstallmentTransaction,
    InstallmentTransactionFromJSON,
    InstallmentTransactionFromJSONTyped,
    InstallmentTransactionToJSON,
} from './InstallmentTransaction';
import type { RecurringTransaction } from './RecurringTransaction';
import {
    instanceOfRecurringTransaction,
    RecurringTransactionFromJSON,
    RecurringTransactionFromJSONTyped,
    RecurringTransactionToJSON,
} from './RecurringTransaction';
import type { TransactionInput } from './TransactionInput';
import {
    instanceOfTransactionInput,
    TransactionInputFromJSON,
    TransactionInputFromJSONTyped,
    TransactionInputToJSON,
} from './TransactionInput';

/**
 * @type CreateTransactionRequest
 * 
 * @export
 */
export type CreateTransactionRequest = InstallmentTransaction | RecurringTransaction | TransactionInput;

export function CreateTransactionRequestFromJSON(json: any): CreateTransactionRequest {
    return CreateTransactionRequestFromJSONTyped(json, false);
}

export function CreateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfInstallmentTransaction(json)) {
        return InstallmentTransactionFromJSONTyped(json, true);
    }
    if (instanceOfRecurringTransaction(json)) {
        return RecurringTransactionFromJSONTyped(json, true);
    }
    if (instanceOfTransactionInput(json)) {
        return TransactionInputFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateTransactionRequestToJSON(json: any): any {
    return CreateTransactionRequestToJSONTyped(json, false);
}

export function CreateTransactionRequestToJSONTyped(value?: CreateTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfInstallmentTransaction(value)) {
        return InstallmentTransactionToJSON(value as InstallmentTransaction);
    }
    if (instanceOfRecurringTransaction(value)) {
        return RecurringTransactionToJSON(value as RecurringTransaction);
    }
    if (instanceOfTransactionInput(value)) {
        return TransactionInputToJSON(value as TransactionInput);
    }
    return {};
}

