/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditCardInvoice
 */
export interface CreditCardInvoice {
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoice
     */
    date: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoice
     */
    startingDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoice
     */
    closingDate: Date;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    paymentAmountCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    balanceCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    previousBalanceCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoice
     */
    creditCardId: number;
}

/**
 * Check if a given object implements the CreditCardInvoice interface.
 */
export function instanceOfCreditCardInvoice(value: object): value is CreditCardInvoice {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('startingDate' in value) || value['startingDate'] === undefined) return false;
    if (!('closingDate' in value) || value['closingDate'] === undefined) return false;
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('paymentAmountCents' in value) || value['paymentAmountCents'] === undefined) return false;
    if (!('balanceCents' in value) || value['balanceCents'] === undefined) return false;
    if (!('previousBalanceCents' in value) || value['previousBalanceCents'] === undefined) return false;
    if (!('creditCardId' in value) || value['creditCardId'] === undefined) return false;
    return true;
}

export function CreditCardInvoiceFromJSON(json: any): CreditCardInvoice {
    return CreditCardInvoiceFromJSONTyped(json, false);
}

export function CreditCardInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditCardInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': (new Date(json['date'])),
        'startingDate': (new Date(json['starting_date'])),
        'closingDate': (new Date(json['closing_date'])),
        'amountCents': json['amount_cents'],
        'paymentAmountCents': json['payment_amount_cents'],
        'balanceCents': json['balance_cents'],
        'previousBalanceCents': json['previous_balance_cents'],
        'creditCardId': json['credit_card_id'],
    };
}

export function CreditCardInvoiceToJSON(json: any): CreditCardInvoice {
    return CreditCardInvoiceToJSONTyped(json, false);
}

export function CreditCardInvoiceToJSONTyped(value?: CreditCardInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'].toISOString().substring(0,10),
        'starting_date': value['startingDate'].toISOString().substring(0,10),
        'closing_date': value['closingDate'].toISOString().substring(0,10),
        'amount_cents': value['amountCents'],
        'payment_amount_cents': value['paymentAmountCents'],
        'balance_cents': value['balanceCents'],
        'previous_balance_cents': value['previousBalanceCents'],
        'credit_card_id': value['creditCardId'],
    };
}

