/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
    TransactionToJSONTyped,
} from './Transaction';

/**
 * 
 * @export
 * @interface CreditCardInvoiceFull
 */
export interface CreditCardInvoiceFull {
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoiceFull
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoiceFull
     */
    date: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoiceFull
     */
    startingDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditCardInvoiceFull
     */
    closingDate: Date;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoiceFull
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoiceFull
     */
    paymentAmountCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoiceFull
     */
    balanceCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoiceFull
     */
    previousBalanceCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInvoiceFull
     */
    creditCardId: number;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof CreditCardInvoiceFull
     */
    transactions: Array<Transaction>;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof CreditCardInvoiceFull
     */
    payments: Array<Transaction>;
}

/**
 * Check if a given object implements the CreditCardInvoiceFull interface.
 */
export function instanceOfCreditCardInvoiceFull(value: object): value is CreditCardInvoiceFull {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('startingDate' in value) || value['startingDate'] === undefined) return false;
    if (!('closingDate' in value) || value['closingDate'] === undefined) return false;
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('paymentAmountCents' in value) || value['paymentAmountCents'] === undefined) return false;
    if (!('balanceCents' in value) || value['balanceCents'] === undefined) return false;
    if (!('previousBalanceCents' in value) || value['previousBalanceCents'] === undefined) return false;
    if (!('creditCardId' in value) || value['creditCardId'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('payments' in value) || value['payments'] === undefined) return false;
    return true;
}

export function CreditCardInvoiceFullFromJSON(json: any): CreditCardInvoiceFull {
    return CreditCardInvoiceFullFromJSONTyped(json, false);
}

export function CreditCardInvoiceFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditCardInvoiceFull {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': (new Date(json['date'])),
        'startingDate': (new Date(json['starting_date'])),
        'closingDate': (new Date(json['closing_date'])),
        'amountCents': json['amount_cents'],
        'paymentAmountCents': json['payment_amount_cents'],
        'balanceCents': json['balance_cents'],
        'previousBalanceCents': json['previous_balance_cents'],
        'creditCardId': json['credit_card_id'],
        'transactions': ((json['transactions'] as Array<any>).map(TransactionFromJSON)),
        'payments': ((json['payments'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function CreditCardInvoiceFullToJSON(json: any): CreditCardInvoiceFull {
    return CreditCardInvoiceFullToJSONTyped(json, false);
}

export function CreditCardInvoiceFullToJSONTyped(value?: CreditCardInvoiceFull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'].toISOString().substring(0,10),
        'starting_date': value['startingDate'].toISOString().substring(0,10),
        'closing_date': value['closingDate'].toISOString().substring(0,10),
        'amount_cents': value['amountCents'],
        'payment_amount_cents': value['paymentAmountCents'],
        'balance_cents': value['balanceCents'],
        'previous_balance_cents': value['previousBalanceCents'],
        'credit_card_id': value['creditCardId'],
        'transactions': ((value['transactions'] as Array<any>).map(TransactionToJSON)),
        'payments': ((value['payments'] as Array<any>).map(TransactionToJSON)),
    };
}

