/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditCard
 */
export interface CreditCard {
    /**
     * 
     * @type {number}
     * @memberof CreditCard
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CreditCard
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreditCard
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCard
     */
    cardNetwork: string;
    /**
     * 
     * @type {number}
     * @memberof CreditCard
     */
    closingDay: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCard
     */
    dueDay: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCard
     */
    limitCents: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreditCard
     */
    archived: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreditCard
     */
    _default: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreditCard
     */
    institutionId: string;
    /**
     * 
     * @type {string}
     * @memberof CreditCard
     */
    institutionName: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreditCard
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditCard
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreditCard
     */
    type: CreditCardTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum CreditCardTypeEnum {
    CreditCard = 'credit_card'
}


/**
 * Check if a given object implements the CreditCard interface.
 */
export function instanceOfCreditCard(value: object): value is CreditCard {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('cardNetwork' in value) || value['cardNetwork'] === undefined) return false;
    if (!('closingDay' in value) || value['closingDay'] === undefined) return false;
    if (!('dueDay' in value) || value['dueDay'] === undefined) return false;
    if (!('limitCents' in value) || value['limitCents'] === undefined) return false;
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('_default' in value) || value['_default'] === undefined) return false;
    if (!('institutionId' in value) || value['institutionId'] === undefined) return false;
    if (!('institutionName' in value) || value['institutionName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CreditCardFromJSON(json: any): CreditCard {
    return CreditCardFromJSONTyped(json, false);
}

export function CreditCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditCard {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'cardNetwork': json['card_network'],
        'closingDay': json['closing_day'],
        'dueDay': json['due_day'],
        'limitCents': json['limit_cents'],
        'archived': json['archived'],
        '_default': json['default'],
        'institutionId': json['institution_id'],
        'institutionName': json['institution_name'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'type': json['type'],
    };
}

export function CreditCardToJSON(json: any): CreditCard {
    return CreditCardToJSONTyped(json, false);
}

export function CreditCardToJSONTyped(value?: CreditCard | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'card_network': value['cardNetwork'],
        'closing_day': value['closingDay'],
        'due_day': value['dueDay'],
        'limit_cents': value['limitCents'],
        'archived': value['archived'],
        'default': value['_default'],
        'institution_id': value['institutionId'],
        'institution_name': value['institutionName'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'type': value['type'],
    };
}

