/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for creating or updating a credit card
 * @export
 * @interface CreditCardInput
 */
export interface CreditCardInput {
    /**
     * 
     * @type {string}
     * @memberof CreditCardInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreditCardInput
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreditCardInput
     */
    cardNetwork?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInput
     */
    closingDay: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInput
     */
    dueDay: number;
    /**
     * 
     * @type {number}
     * @memberof CreditCardInput
     */
    limitCents?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreditCardInput
     */
    archived?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreditCardInput
     */
    _default?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreditCardInput
     */
    institutionId?: string;
}

/**
 * Check if a given object implements the CreditCardInput interface.
 */
export function instanceOfCreditCardInput(value: object): value is CreditCardInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('closingDay' in value) || value['closingDay'] === undefined) return false;
    if (!('dueDay' in value) || value['dueDay'] === undefined) return false;
    return true;
}

export function CreditCardInputFromJSON(json: any): CreditCardInput {
    return CreditCardInputFromJSONTyped(json, false);
}

export function CreditCardInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditCardInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'cardNetwork': json['card_network'] == null ? undefined : json['card_network'],
        'closingDay': json['closing_day'],
        'dueDay': json['due_day'],
        'limitCents': json['limit_cents'] == null ? undefined : json['limit_cents'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        '_default': json['default'] == null ? undefined : json['default'],
        'institutionId': json['institution_id'] == null ? undefined : json['institution_id'],
    };
}

export function CreditCardInputToJSON(json: any): CreditCardInput {
    return CreditCardInputToJSONTyped(json, false);
}

export function CreditCardInputToJSONTyped(value?: CreditCardInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'card_network': value['cardNetwork'],
        'closing_day': value['closingDay'],
        'due_day': value['dueDay'],
        'limit_cents': value['limitCents'],
        'archived': value['archived'],
        'default': value['_default'],
        'institution_id': value['institutionId'],
    };
}

