/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTransactionRequest
 */
export interface DeleteTransactionRequest {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteTransactionRequest
     */
    updateFuture?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteTransactionRequest
     */
    updateAll?: boolean;
}

/**
 * Check if a given object implements the DeleteTransactionRequest interface.
 */
export function instanceOfDeleteTransactionRequest(value: object): value is DeleteTransactionRequest {
    return true;
}

export function DeleteTransactionRequestFromJSON(json: any): DeleteTransactionRequest {
    return DeleteTransactionRequestFromJSONTyped(json, false);
}

export function DeleteTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'updateFuture': json['update_future'] == null ? undefined : json['update_future'],
        'updateAll': json['update_all'] == null ? undefined : json['update_all'],
    };
}

export function DeleteTransactionRequestToJSON(json: any): DeleteTransactionRequest {
    return DeleteTransactionRequestToJSONTyped(json, false);
}

export function DeleteTransactionRequestToJSONTyped(value?: DeleteTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'update_future': value['updateFuture'],
        'update_all': value['updateAll'],
    };
}

