/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Failed Authentication
 * @export
 * @interface FailedAuthentication
 */
export interface FailedAuthentication {
    /**
     * 
     * @type {string}
     * @memberof FailedAuthentication
     */
    error?: FailedAuthenticationErrorEnum;
}

/**
* @export
* @enum {string}
*/
export enum FailedAuthenticationErrorEnum {
    NoAutorizado = 'Não autorizado'
}


/**
 * Check if a given object implements the FailedAuthentication interface.
 */
export function instanceOfFailedAuthentication(value: object): value is FailedAuthentication {
    return true;
}

export function FailedAuthenticationFromJSON(json: any): FailedAuthentication {
    return FailedAuthenticationFromJSONTyped(json, false);
}

export function FailedAuthenticationFromJSONTyped(json: any, ignoreDiscriminator: boolean): FailedAuthentication {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FailedAuthenticationToJSON(json: any): FailedAuthentication {
    return FailedAuthenticationToJSONTyped(json, false);
}

export function FailedAuthenticationToJSONTyped(value?: FailedAuthentication | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

