/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstallmentTransactionAllOfInstallmentsAttributes
 */
export interface InstallmentTransactionAllOfInstallmentsAttributes {
    /**
     * 
     * @type {number}
     * @memberof InstallmentTransactionAllOfInstallmentsAttributes
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof InstallmentTransactionAllOfInstallmentsAttributes
     */
    periodicity: InstallmentTransactionAllOfInstallmentsAttributesPeriodicityEnum;
}

/**
* @export
* @enum {string}
*/
export enum InstallmentTransactionAllOfInstallmentsAttributesPeriodicityEnum {
    Monthly = 'monthly',
    Yearly = 'yearly',
    Weekly = 'weekly',
    Biweekly = 'biweekly',
    Bimonthly = 'bimonthly',
    Trimonthly = 'trimonthly'
}


/**
 * Check if a given object implements the InstallmentTransactionAllOfInstallmentsAttributes interface.
 */
export function instanceOfInstallmentTransactionAllOfInstallmentsAttributes(value: object): value is InstallmentTransactionAllOfInstallmentsAttributes {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('periodicity' in value) || value['periodicity'] === undefined) return false;
    return true;
}

export function InstallmentTransactionAllOfInstallmentsAttributesFromJSON(json: any): InstallmentTransactionAllOfInstallmentsAttributes {
    return InstallmentTransactionAllOfInstallmentsAttributesFromJSONTyped(json, false);
}

export function InstallmentTransactionAllOfInstallmentsAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallmentTransactionAllOfInstallmentsAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'periodicity': json['periodicity'],
    };
}

export function InstallmentTransactionAllOfInstallmentsAttributesToJSON(json: any): InstallmentTransactionAllOfInstallmentsAttributes {
    return InstallmentTransactionAllOfInstallmentsAttributesToJSONTyped(json, false);
}

export function InstallmentTransactionAllOfInstallmentsAttributesToJSONTyped(value?: InstallmentTransactionAllOfInstallmentsAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'periodicity': value['periodicity'],
    };
}

