/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecurringTransactionAllOfRecurrenceAttributes
 */
export interface RecurringTransactionAllOfRecurrenceAttributes {
    /**
     * 
     * @type {string}
     * @memberof RecurringTransactionAllOfRecurrenceAttributes
     */
    periodicity: RecurringTransactionAllOfRecurrenceAttributesPeriodicityEnum;
}

/**
* @export
* @enum {string}
*/
export enum RecurringTransactionAllOfRecurrenceAttributesPeriodicityEnum {
    Monthly = 'monthly',
    Yearly = 'yearly',
    Weekly = 'weekly',
    Biweekly = 'biweekly',
    Bimonthly = 'bimonthly',
    Trimonthly = 'trimonthly'
}


/**
 * Check if a given object implements the RecurringTransactionAllOfRecurrenceAttributes interface.
 */
export function instanceOfRecurringTransactionAllOfRecurrenceAttributes(value: object): value is RecurringTransactionAllOfRecurrenceAttributes {
    if (!('periodicity' in value) || value['periodicity'] === undefined) return false;
    return true;
}

export function RecurringTransactionAllOfRecurrenceAttributesFromJSON(json: any): RecurringTransactionAllOfRecurrenceAttributes {
    return RecurringTransactionAllOfRecurrenceAttributesFromJSONTyped(json, false);
}

export function RecurringTransactionAllOfRecurrenceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringTransactionAllOfRecurrenceAttributes {
    if (json == null) {
        return json;
    }
    return {
        
        'periodicity': json['periodicity'],
    };
}

export function RecurringTransactionAllOfRecurrenceAttributesToJSON(json: any): RecurringTransactionAllOfRecurrenceAttributes {
    return RecurringTransactionAllOfRecurrenceAttributesToJSONTyped(json, false);
}

export function RecurringTransactionAllOfRecurrenceAttributesToJSONTyped(value?: RecurringTransactionAllOfRecurrenceAttributes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'periodicity': value['periodicity'],
    };
}

