/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionTagsInner } from './TransactionTagsInner';
import {
    TransactionTagsInnerFromJSON,
    TransactionTagsInnerFromJSONTyped,
    TransactionTagsInnerToJSON,
    TransactionTagsInnerToJSONTyped,
} from './TransactionTagsInner';
import type { RecurringTransactionAllOfRecurrenceAttributes } from './RecurringTransactionAllOfRecurrenceAttributes';
import {
    RecurringTransactionAllOfRecurrenceAttributesFromJSON,
    RecurringTransactionAllOfRecurrenceAttributesFromJSONTyped,
    RecurringTransactionAllOfRecurrenceAttributesToJSON,
    RecurringTransactionAllOfRecurrenceAttributesToJSONTyped,
} from './RecurringTransactionAllOfRecurrenceAttributes';

/**
 * Recurring Transaction
 * @export
 * @interface RecurringTransaction
 */
export interface RecurringTransaction {
    /**
     * ID of the Transaction
     * @type {number}
     * @memberof RecurringTransaction
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RecurringTransaction
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof RecurringTransaction
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof RecurringTransaction
     */
    paid: boolean;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    amountCents: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    totalInstallments: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    installment: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecurringTransaction
     */
    recurring: boolean;
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof RecurringTransaction
     */
    accountId: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    categoryId: number;
    /**
     * 
     * @type {string}
     * @memberof RecurringTransaction
     */
    notes: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    attachmentsCount: number;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    creditCardId: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    creditCardInvoiceId: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    paidCreditCardId: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    paidCreditCardInvoiceId: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    opositeTransactionId: number | null;
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof RecurringTransaction
     */
    opositeAccountId: number | null;
    /**
     * 
     * @type {Date}
     * @memberof RecurringTransaction
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecurringTransaction
     */
    updatedAt: Date;
    /**
     * 
     * @type {Array<TransactionTagsInner>}
     * @memberof RecurringTransaction
     */
    tags: Array<TransactionTagsInner> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecurringTransaction
     */
    attachments: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof RecurringTransaction
     */
    recurrenceId: number | null;
    /**
     * 
     * @type {RecurringTransactionAllOfRecurrenceAttributes}
     * @memberof RecurringTransaction
     */
    recurrenceAttributes: RecurringTransactionAllOfRecurrenceAttributes;
}

/**
 * Check if a given object implements the RecurringTransaction interface.
 */
export function instanceOfRecurringTransaction(value: object): value is RecurringTransaction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('paid' in value) || value['paid'] === undefined) return false;
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('totalInstallments' in value) || value['totalInstallments'] === undefined) return false;
    if (!('installment' in value) || value['installment'] === undefined) return false;
    if (!('recurring' in value) || value['recurring'] === undefined) return false;
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('attachmentsCount' in value) || value['attachmentsCount'] === undefined) return false;
    if (!('creditCardId' in value) || value['creditCardId'] === undefined) return false;
    if (!('creditCardInvoiceId' in value) || value['creditCardInvoiceId'] === undefined) return false;
    if (!('paidCreditCardId' in value) || value['paidCreditCardId'] === undefined) return false;
    if (!('paidCreditCardInvoiceId' in value) || value['paidCreditCardInvoiceId'] === undefined) return false;
    if (!('opositeTransactionId' in value) || value['opositeTransactionId'] === undefined) return false;
    if (!('opositeAccountId' in value) || value['opositeAccountId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('attachments' in value) || value['attachments'] === undefined) return false;
    if (!('recurrenceId' in value) || value['recurrenceId'] === undefined) return false;
    if (!('recurrenceAttributes' in value) || value['recurrenceAttributes'] === undefined) return false;
    return true;
}

export function RecurringTransactionFromJSON(json: any): RecurringTransaction {
    return RecurringTransactionFromJSONTyped(json, false);
}

export function RecurringTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
        'date': (new Date(json['date'])),
        'paid': json['paid'],
        'amountCents': json['amount_cents'],
        'totalInstallments': json['total_installments'],
        'installment': json['installment'],
        'recurring': json['recurring'],
        'accountId': json['account_id'],
        'categoryId': json['category_id'],
        'notes': json['notes'],
        'attachmentsCount': json['attachments_count'],
        'creditCardId': json['credit_card_id'],
        'creditCardInvoiceId': json['credit_card_invoice_id'],
        'paidCreditCardId': json['paid_credit_card_id'],
        'paidCreditCardInvoiceId': json['paid_credit_card_invoice_id'],
        'opositeTransactionId': json['oposite_transaction_id'],
        'opositeAccountId': json['oposite_account_id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'tags': (json['tags'] == null ? null : (json['tags'] as Array<any>).map(TransactionTagsInnerFromJSON)),
        'attachments': json['attachments'] == null ? null : json['attachments'],
        'recurrenceId': json['recurrence_id'],
        'recurrenceAttributes': RecurringTransactionAllOfRecurrenceAttributesFromJSON(json['recurrence_attributes']),
    };
}

export function RecurringTransactionToJSON(json: any): RecurringTransaction {
    return RecurringTransactionToJSONTyped(json, false);
}

export function RecurringTransactionToJSONTyped(value?: RecurringTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'date': value['date'].toISOString().substring(0,10),
        'paid': value['paid'],
        'amount_cents': value['amountCents'],
        'total_installments': value['totalInstallments'],
        'installment': value['installment'],
        'recurring': value['recurring'],
        'account_id': value['accountId'],
        'category_id': value['categoryId'],
        'notes': value['notes'],
        'attachments_count': value['attachmentsCount'],
        'credit_card_id': value['creditCardId'],
        'credit_card_invoice_id': value['creditCardInvoiceId'],
        'paid_credit_card_id': value['paidCreditCardId'],
        'paid_credit_card_invoice_id': value['paidCreditCardInvoiceId'],
        'oposite_transaction_id': value['opositeTransactionId'],
        'oposite_account_id': value['opositeAccountId'],
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
        'tags': (value['tags'] == null ? null : (value['tags'] as Array<any>).map(TransactionTagsInnerToJSON)),
        'attachments': value['attachments'],
        'recurrence_id': value['recurrenceId'],
        'recurrence_attributes': RecurringTransactionAllOfRecurrenceAttributesToJSON(value['recurrenceAttributes']),
    };
}

