/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Tag } from './Tag';
import {
    instanceOfTag,
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './Tag';

/**
 * @type TransactionTagsInner
 * 
 * @export
 */
export type TransactionTagsInner = Tag | string;

export function TransactionTagsInnerFromJSON(json: any): TransactionTagsInner {
    return TransactionTagsInnerFromJSONTyped(json, false);
}

export function TransactionTagsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionTagsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfTag(json)) {
        return TagFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function TransactionTagsInnerToJSON(json: any): any {
    return TransactionTagsInnerToJSONTyped(json, false);
}

export function TransactionTagsInnerToJSONTyped(value?: TransactionTagsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfTag(value)) {
        return TagToJSON(value as Tag);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

