/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * Schema for creating a transaction
 * @export
 * @interface TransactionInput
 */
export interface TransactionInput {
    /**
     * 
     * @type {string}
     * @memberof TransactionInput
     */
    description: string;
    /**
     * 
     * @type {Date}
     * @memberof TransactionInput
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionInput
     */
    paid?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TransactionInput
     */
    amountCents: number;
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof TransactionInput
     */
    accountId?: number;
    /**
     * 
     * @type {number}
     * @memberof TransactionInput
     */
    categoryId: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionInput
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionInput
     */
    creditCardId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TransactionInput
     */
    creditCardInvoiceId?: number | null;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof TransactionInput
     */
    tags?: Array<Tag>;
}

/**
 * Check if a given object implements the TransactionInput interface.
 */
export function instanceOfTransactionInput(value: object): value is TransactionInput {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('amountCents' in value) || value['amountCents'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    return true;
}

export function TransactionInputFromJSON(json: any): TransactionInput {
    return TransactionInputFromJSONTyped(json, false);
}

export function TransactionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'date': (new Date(json['date'])),
        'paid': json['paid'] == null ? undefined : json['paid'],
        'amountCents': json['amount_cents'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'categoryId': json['category_id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'creditCardId': json['credit_card_id'] == null ? undefined : json['credit_card_id'],
        'creditCardInvoiceId': json['credit_card_invoice_id'] == null ? undefined : json['credit_card_invoice_id'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
    };
}

export function TransactionInputToJSON(json: any): TransactionInput {
    return TransactionInputToJSONTyped(json, false);
}

export function TransactionInputToJSONTyped(value?: TransactionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'date': value['date'].toISOString().substring(0,10),
        'paid': value['paid'],
        'amount_cents': value['amountCents'],
        'account_id': value['accountId'],
        'category_id': value['categoryId'],
        'notes': value['notes'],
        'credit_card_id': value['creditCardId'],
        'credit_card_invoice_id': value['creditCardInvoiceId'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
    };
}

