/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * 
 * @export
 * @interface UpdateTransactionRequest
 */
export interface UpdateTransactionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionRequest
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTransactionRequest
     */
    date?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransactionRequest
     */
    paid?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionRequest
     */
    amountCents?: number;
    /**
     * ID of the Bank Account
     * @type {number}
     * @memberof UpdateTransactionRequest
     */
    accountId?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionRequest
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionRequest
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionRequest
     */
    creditCardId?: number | null;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof UpdateTransactionRequest
     */
    tags?: Array<Tag>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransactionRequest
     */
    updateFuture?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTransactionRequest
     */
    updateAll?: boolean;
}

/**
 * Check if a given object implements the UpdateTransactionRequest interface.
 */
export function instanceOfUpdateTransactionRequest(value: object): value is UpdateTransactionRequest {
    return true;
}

export function UpdateTransactionRequestFromJSON(json: any): UpdateTransactionRequest {
    return UpdateTransactionRequestFromJSONTyped(json, false);
}

export function UpdateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'paid': json['paid'] == null ? undefined : json['paid'],
        'amountCents': json['amount_cents'] == null ? undefined : json['amount_cents'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'creditCardId': json['credit_card_id'] == null ? undefined : json['credit_card_id'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
        'updateFuture': json['update_future'] == null ? undefined : json['update_future'],
        'updateAll': json['update_all'] == null ? undefined : json['update_all'],
    };
}

export function UpdateTransactionRequestToJSON(json: any): UpdateTransactionRequest {
    return UpdateTransactionRequestToJSONTyped(json, false);
}

export function UpdateTransactionRequestToJSONTyped(value?: UpdateTransactionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'paid': value['paid'],
        'amount_cents': value['amountCents'],
        'account_id': value['accountId'],
        'category_id': value['categoryId'],
        'notes': value['notes'],
        'credit_card_id': value['creditCardId'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
        'update_future': value['updateFuture'],
        'update_all': value['updateAll'],
    };
}

