/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Budget,
  FailedAuthentication,
  NotFound,
} from '../models/index';
import {
    BudgetFromJSON,
    BudgetToJSON,
    FailedAuthenticationFromJSON,
    FailedAuthenticationToJSON,
    NotFoundFromJSON,
    NotFoundToJSON,
} from '../models/index';

export interface ListAnnualBudgetsRequest {
    year: number;
}

export interface ListMonthlyBudgetsRequest {
    year: number;
    month: number;
}

/**
 * 
 */
export class BudgetsApi extends runtime.BaseAPI {

    /**
     * Get Annual Budgets
     */
    async listAnnualBudgetsRaw(requestParameters: ListAnnualBudgetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Budget>>> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling listAnnualBudgets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/budgets/{year}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BudgetFromJSON));
    }

    /**
     * Get Annual Budgets
     */
    async listAnnualBudgets(requestParameters: ListAnnualBudgetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Budget>> {
        const response = await this.listAnnualBudgetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Current Month Budgets
     */
    async listCurrentMonthBudgetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Budget>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/budgets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BudgetFromJSON));
    }

    /**
     * Get Current Month Budgets
     */
    async listCurrentMonthBudgets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Budget>> {
        const response = await this.listCurrentMonthBudgetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Monthly Budgets
     */
    async listMonthlyBudgetsRaw(requestParameters: ListMonthlyBudgetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Budget>>> {
        if (requestParameters['year'] == null) {
            throw new runtime.RequiredError(
                'year',
                'Required parameter "year" was null or undefined when calling listMonthlyBudgets().'
            );
        }

        if (requestParameters['month'] == null) {
            throw new runtime.RequiredError(
                'month',
                'Required parameter "month" was null or undefined when calling listMonthlyBudgets().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/budgets/{year}/{month}`;
        urlPath = urlPath.replace(`{${"year"}}`, encodeURIComponent(String(requestParameters['year'])));
        urlPath = urlPath.replace(`{${"month"}}`, encodeURIComponent(String(requestParameters['month'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BudgetFromJSON));
    }

    /**
     * Get Monthly Budgets
     */
    async listMonthlyBudgets(requestParameters: ListMonthlyBudgetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Budget>> {
        const response = await this.listMonthlyBudgetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
