/* tslint:disable */
/* eslint-disable */
/**
 * Organizze API
 * Specification for the Organizze API described in [https://github.com/organizze/api-doc](https://github.com/organizze/api-doc)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreditCard,
  CreditCardInput,
  CreditCardInvoice,
  CreditCardInvoiceFull,
  FailedAuthentication,
  NotFound,
  Transaction,
  ValidationError,
} from '../models/index';
import {
    CreditCardFromJSON,
    CreditCardToJSON,
    CreditCardInputFromJSON,
    CreditCardInputToJSON,
    CreditCardInvoiceFromJSON,
    CreditCardInvoiceToJSON,
    CreditCardInvoiceFullFromJSON,
    CreditCardInvoiceFullToJSON,
    FailedAuthenticationFromJSON,
    FailedAuthenticationToJSON,
    NotFoundFromJSON,
    NotFoundToJSON,
    TransactionFromJSON,
    TransactionToJSON,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from '../models/index';

export interface CreateCreditCardRequest {
    creditCardInput: CreditCardInput;
}

export interface DeleteCreditCardRequest {
    creditCardID: number;
}

export interface ListCreditCardInvoicePaymentsRequest {
    creditCardID: number;
    creditCardInvoiceID: number;
}

export interface ListCreditCardInvoicesRequest {
    creditCardID: number;
    startDate?: Date;
    endDate?: Date;
}

export interface ReadCreditCardRequest {
    creditCardID: number;
}

export interface ReadCreditCardInvoiceRequest {
    creditCardID: number;
    creditCardInvoiceID: number;
}

export interface UpdateCreditCardRequest {
    creditCardID: number;
    creditCardInput: CreditCardInput;
}

/**
 * 
 */
export class CreditCardsApi extends runtime.BaseAPI {

    /**
     * Create Credit Card
     */
    async createCreditCardRaw(requestParameters: CreateCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditCard>> {
        if (requestParameters['creditCardInput'] == null) {
            throw new runtime.RequiredError(
                'creditCardInput',
                'Required parameter "creditCardInput" was null or undefined when calling createCreditCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreditCardInputToJSON(requestParameters['creditCardInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditCardFromJSON(jsonValue));
    }

    /**
     * Create Credit Card
     */
    async createCreditCard(requestParameters: CreateCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditCard> {
        const response = await this.createCreditCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Credit Card
     */
    async deleteCreditCardRaw(requestParameters: DeleteCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditCard>> {
        if (requestParameters['creditCardID'] == null) {
            throw new runtime.RequiredError(
                'creditCardID',
                'Required parameter "creditCardID" was null or undefined when calling deleteCreditCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards/{creditCardID}`;
        urlPath = urlPath.replace(`{${"creditCardID"}}`, encodeURIComponent(String(requestParameters['creditCardID'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditCardFromJSON(jsonValue));
    }

    /**
     * Delete Credit Card
     */
    async deleteCreditCard(requestParameters: DeleteCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditCard> {
        const response = await this.deleteCreditCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Credit Card Invoice Payments
     */
    async listCreditCardInvoicePaymentsRaw(requestParameters: ListCreditCardInvoicePaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Transaction>>> {
        if (requestParameters['creditCardID'] == null) {
            throw new runtime.RequiredError(
                'creditCardID',
                'Required parameter "creditCardID" was null or undefined when calling listCreditCardInvoicePayments().'
            );
        }

        if (requestParameters['creditCardInvoiceID'] == null) {
            throw new runtime.RequiredError(
                'creditCardInvoiceID',
                'Required parameter "creditCardInvoiceID" was null or undefined when calling listCreditCardInvoicePayments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards/{creditCardID}/invoices/{creditCardInvoiceID}/payments`;
        urlPath = urlPath.replace(`{${"creditCardID"}}`, encodeURIComponent(String(requestParameters['creditCardID'])));
        urlPath = urlPath.replace(`{${"creditCardInvoiceID"}}`, encodeURIComponent(String(requestParameters['creditCardInvoiceID'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TransactionFromJSON));
    }

    /**
     * List Credit Card Invoice Payments
     */
    async listCreditCardInvoicePayments(requestParameters: ListCreditCardInvoicePaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Transaction>> {
        const response = await this.listCreditCardInvoicePaymentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Credit Card Invoices
     */
    async listCreditCardInvoicesRaw(requestParameters: ListCreditCardInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CreditCardInvoice>>> {
        if (requestParameters['creditCardID'] == null) {
            throw new runtime.RequiredError(
                'creditCardID',
                'Required parameter "creditCardID" was null or undefined when calling listCreditCardInvoices().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards/{creditCardID}/invoices`;
        urlPath = urlPath.replace(`{${"creditCardID"}}`, encodeURIComponent(String(requestParameters['creditCardID'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CreditCardInvoiceFromJSON));
    }

    /**
     * List Credit Card Invoices
     */
    async listCreditCardInvoices(requestParameters: ListCreditCardInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CreditCardInvoice>> {
        const response = await this.listCreditCardInvoicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Credit Cards
     */
    async listCreditCardsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CreditCard>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CreditCardFromJSON));
    }

    /**
     * List Credit Cards
     */
    async listCreditCards(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CreditCard>> {
        const response = await this.listCreditCardsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Read Credit Card
     */
    async readCreditCardRaw(requestParameters: ReadCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditCard>> {
        if (requestParameters['creditCardID'] == null) {
            throw new runtime.RequiredError(
                'creditCardID',
                'Required parameter "creditCardID" was null or undefined when calling readCreditCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards/{creditCardID}`;
        urlPath = urlPath.replace(`{${"creditCardID"}}`, encodeURIComponent(String(requestParameters['creditCardID'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditCardFromJSON(jsonValue));
    }

    /**
     * Read Credit Card
     */
    async readCreditCard(requestParameters: ReadCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditCard> {
        const response = await this.readCreditCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Read Credit Card Invoice
     */
    async readCreditCardInvoiceRaw(requestParameters: ReadCreditCardInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditCardInvoiceFull>> {
        if (requestParameters['creditCardID'] == null) {
            throw new runtime.RequiredError(
                'creditCardID',
                'Required parameter "creditCardID" was null or undefined when calling readCreditCardInvoice().'
            );
        }

        if (requestParameters['creditCardInvoiceID'] == null) {
            throw new runtime.RequiredError(
                'creditCardInvoiceID',
                'Required parameter "creditCardInvoiceID" was null or undefined when calling readCreditCardInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards/{creditCardID}/invoices/{creditCardInvoiceID}`;
        urlPath = urlPath.replace(`{${"creditCardID"}}`, encodeURIComponent(String(requestParameters['creditCardID'])));
        urlPath = urlPath.replace(`{${"creditCardInvoiceID"}}`, encodeURIComponent(String(requestParameters['creditCardInvoiceID'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditCardInvoiceFullFromJSON(jsonValue));
    }

    /**
     * Read Credit Card Invoice
     */
    async readCreditCardInvoice(requestParameters: ReadCreditCardInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditCardInvoiceFull> {
        const response = await this.readCreditCardInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Credit Card
     */
    async updateCreditCardRaw(requestParameters: UpdateCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditCard>> {
        if (requestParameters['creditCardID'] == null) {
            throw new runtime.RequiredError(
                'creditCardID',
                'Required parameter "creditCardID" was null or undefined when calling updateCreditCard().'
            );
        }

        if (requestParameters['creditCardInput'] == null) {
            throw new runtime.RequiredError(
                'creditCardInput',
                'Required parameter "creditCardInput" was null or undefined when calling updateCreditCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["User-Agent"] = await this.configuration.apiKey("User-Agent"); // userAgent authentication
        }


        let urlPath = `/credit_cards/{creditCardID}`;
        urlPath = urlPath.replace(`{${"creditCardID"}}`, encodeURIComponent(String(requestParameters['creditCardID'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreditCardInputToJSON(requestParameters['creditCardInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditCardFromJSON(jsonValue));
    }

    /**
     * Update Credit Card
     */
    async updateCreditCard(requestParameters: UpdateCreditCardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditCard> {
        const response = await this.updateCreditCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
